### ISSUE TITLE
About seaborn required by provis

### ISSUE THREAD

**Issue by Stfort52** [salesforce/provis#11]
# Problem

By now, running the install script yields `numpy==1.24.2`
<details>
    <summary>installation output(click to expand)</summary>

```
Searching for numpy
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/9c/ee/77768cade9607687fadbcc1dcbb82dba0554154b3aa641f9c17233ffabe8/numpy-1.24.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=2eabd64ddb96a1239791da78fa5f4e1693ae2dadc82a76bc76a14cbb2b966e96
Best match: numpy 1.24.2
Processing numpy-1.24.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Installing numpy-1.24.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /usr/local/lib/python3.8/dist-packages
Adding numpy 1.24.2 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.8 script to /usr/local/bin

Installed /usr/local/lib/python3.8/dist-packages/numpy-1.24.2-py3.8-linux-x86_64.egg
```
</details>

And, this version of numpy is not compatable with `seaborn==0.10.1` which is a dependency of provis.
This fails as this version of seaborn internally uses `np.bool` which is deprecated in `numpy>=1.20`.
As a result, all `report_*.py` scripts fail, yielding the following error.

<details>
    <summary>error (click to expand)</summary>

```py
report_edge_features.py:27: MatplotlibDeprecationWarning:                                                                                
The mpl_toolkits.axes_grid1.colorbar module was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use matplotlib
.colorbar instead.                                                                                                                       
  from mpl_toolkits.axes_grid1.colorbar import colorbar                                                                                  
Namespace(exp_name='edge_features_contact_tape_bert')                                                                                    
Namespace(dataset='proteinnet', exp_name='edge_features_contact_tape_bert', features=['contact_map'], max_seq_len=512, min_attn=0.3, mode
l='bert', model_dir=None, model_version=None, no_cuda=True, num_sequences=5000, seed=123, shuffle=True)                                  
/usr/local/lib/python3.8/dist-packages/seaborn-0.10.1-py3.8.egg/seaborn/matrix.py:78: FutureWarning: In the future `np.bool` will be defi
ned as the corresponding NumPy scalar.                                                                                                   
  dtype=np.bool)                                                                                                                         
Traceback (most recent call last):                                                                                                       
  File "report_edge_features.py", line 147, in <module>                                                                                  
    create_figure(feature_name, weighted_sum, weight_total, report_dir, min_total=min_total, filetype=filetype)                          
  File "report_edge_features.py", line 69, in create_figure                                                                              
    heatmap = sns.heatmap((mean_by_head * 100).tolist(), center=0.0, ax=ax1,                                                             
  File "/usr/local/lib/python3.8/dist-packages/seaborn-0.10.1-py3.8.egg/seaborn/matrix.py", line 535, in heatmap                         
    plotter = _HeatMapper(data, vmin, vmax, cmap, center, robust, annot, fmt,                                                            
  File "/usr/local/lib/python3.8/dist-packages/seaborn-0.10.1-py3.8.egg/seaborn/matrix.py", line 111, in __init__                        
    mask = _matrix_mask(data, mask)                                                                                                      
  File "/usr/local/lib/python3.8/dist-packages/seaborn-0.10.1-py3.8.egg/seaborn/matrix.py", line 78, in _matrix_mask                     
    dtype=np.bool)                                                                                                                       
  File "/usr/local/lib/python3.8/dist-packages/numpy-1.24.2-py3.8-linux-x86_64.egg/numpy/__init__.py", line 305, in __getattr__          
    raise AttributeError(__former_attrs__[attr])                                                                                         
AttributeError: module 'numpy' has no attribute 'bool'.                                                                                  
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not 
modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.                                  
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:                     
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations 
```
</details>

Therefore, I strongly suggest recommend bumping up the `seaborn` version or downgrading `numpy`. 

Forcing the installation of `seaborn==0.12.2` solved the problem for me.
```
cmyc@oncogene:~/provis/protein_attention/attention_analysis$ python -m pip check                                                                                                                                                                                             
fpygobject 3.36.0 requires pycairo, which is not installed.                                                                              
ipywidgets 7.7.3 has requirement jupyterlab-widgets<3,>=1.0.0; python_version >= "3.6", but you have jupyterlab-widgets 3.0.5.           
ipywidgets 7.7.3 has requirement widgetsnbextension~=3.6.0, but you have widgetsnbextension 4.0.5.                                       
provis 0.0.1 has requirement seaborn==0.10.1, but you have seaborn 0.12.2.
```

# Version Info
```
cmyc@oncogene:~/provis/protein_attention/attention_analysis$ py -V
Python 3.8.10
cmyc@oncogene:~/provis/protein_attention/attention_analysis$ uname -a
Linux oncogene 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jessevig** [comment]
Hi @Stfort52 thanks so much for catching this, and apologies for the delayed response. I've implemented your suggested fix. Very much appreciated!
